[platformio]
build_dir = ~\.pio_build\Code_AI

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Tốc độ Serial Monitor
monitor_speed = 115200

; Cấu hình RAM cho N16R8 (8MB PSRAM OPI)
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv

; Cấu hình biên dịch
build_flags = 
    -DCORE_DEBUG_LEVEL=5
    -DBOARD_HAS_PSRAM

lib_deps = 
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit ST7735 and ST7789 Library@^1.10.3
    bblanchon/ArduinoJson@^7.0.4
    earlephilhower/ESP8266Audio@^1.9.7
    tzapu/WiFiManager@^2.0.16-rc.2
